export const ADD_USER='ADD_USER';
export const UPDATE_USER='UPDATE_USER';
export const REMOVE_USER='REMOVE_USER'

export const ADD_SCHEDULE='ADD_SCHEDULE';
export const ADD_SCHEDULEs='ADD_SCHEDULEs';
export const REMOVE_SCHEDULE='REMOVE_SCHEDULE';
export const UPDATE_SCHEDULE='UPDATE_SCHEDULE';
export const CLEAR_SCHEDULES='CLEAR_SCHEDULES';

export const SET_DATES='SET_DATES';
export const ADD_SHIFTTIMES='ADD_SHIFTTIMES';

export const ADD_SHIFTLABEL='ADD_SHIFTLABEL';

export const ADD_REQUEST_OFF = 'ADD_REQUEST_OFF'
export const UPDATE_REQUEST_OFF = 'UPDATE_REQUEST_OFF'
export const REMOVE_REQUEST_OFF = 'REMOVE_REQUEST_OFF'